import { VideoProject } from "@/types/videos";

export const videoProjectsData: VideoProject[] = [
  {
    id: 1,
    video_title: "একজন ফেসবুক ইঞ্জিনিয়ারের রিজিউমি কেমন হয়?",
    video_description: `How to Build Your Perfect Resume: Learn from a FAANG Employee Example! Are you ready to take your career to new heights and secure your dream job at a top tech company? Join us on this exclusive journey inside the mind of a FAANG employee as we unveil the secrets of their perfect resume! In this eye-opening video, you'll discover the exact strategies and tips used by the industry's finest to stand out from the crowd and impress recruiters.`,
    tags: ["Talking Head", "Tech Review", "Color Grading", "Professional"],
    cover_image: "rVVeLdouViU",
    publish_date: "2024-08-04",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/rVVeLdouViU?si=LwWPmI4F34mwLNw8",
    project_images: [
      "/placeholder.svg?height=200&width=300",
      "/placeholder.svg?height=200&width=300",
    ],
    category: "Talking Head",
    duration: "6:32",
    software_used: ["DaVinci Resolve", "After Effects"],
  },
  {
    id: 2,
    video_title: "Mastering DSA for Developers | Last Call to Join",
    video_description:
      "This workshop helps application developers explore DSA through real-world problems, connecting data structures to business challenges and fostering a problem-solving mindset for practical solutions.",
    tags: ["Education", "Graphics", "Audio Sync", "Professional"],
    cover_image: "JSZmQxg3fos",
    publish_date: "2025-04-08",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/JSZmQxg3fos?si=NZYmG1g4mZiYx6Eb",
    project_images: ["/placeholder.svg?height=200&width=300"],
    category: "Talking Head",
    duration: "10:12",
    software_used: ["Premiere Pro", "After Effects"],
  },
  {
    id: 3,
    video_title: "Apply logic to simplify your conditional problems",
    video_description:
      "Apply logic to simplify your conditional problems. Watch the video to understand how!",
    tags: ["Short Form", "Social Media", "Dynamic", "Viral"],
    cover_image: "Qwwgg_qt5ew",
    publish_date: "2025-01-16",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/Qwwgg_qt5ew?si=tTSoTUnuVPdjpc7y",
    project_images: ["/placeholder.svg?height=200&width=300"],
    category: "Shorts",
    duration: "2:44",
    software_used: ["DaVinci Resolve"],
  },
  {
    id: 4,
    video_title: "EduNurture360 কি? | Edu Bridge Academy",
    video_description: "শুরু হয়ে গেছে EduNurture360 এর ২০২৪ সালের ব্যাচ!",
    tags: ["Promo", "Branding", "Cinematic", "Professional"],
    cover_image: "kpJyIq-mvtc",
    publish_date: "2024-02-01",
    client_name: "Edu Bridge Academy",
    client_image: "/companies/edu-bridge-academy.jpg",
    client_feedback: "",
    video_link: "https://youtu.be/kpJyIq-mvtc?si=wdURtwH9HI1FZmOR",
    project_images: [
      "/placeholder.svg?height=200&width=300",
      "/placeholder.svg?height=200&width=300",
    ],
    category: "Promo",
    duration: "1:28",
    software_used: ["DaVinci Resolve", "After Effects"],
  },
  {
    id: 5,
    video_title: "EcoRevoluation Documentary",
    video_description: "EcoRevoluation Documentary",
    tags: ["Documentary", "Storytelling", "Interviews", "Cinematic"],
    cover_image: "Y3lWN7oFkpw",
    publish_date: "2025-04-12",
    client_name: "EcoRevolution",
    client_image: "/companies/eco-revolution.jpg",
    client_feedback: "",
    video_link: "https://youtu.be/Y3lWN7oFkpw",
    project_images: ["/placeholder.svg?height=200&width=300"],
    category: "Documentary",
    duration: "3:51",
    software_used: ["DaVinci Resolve", "Audition"],
  },
  {
    id: 6,
    video_title: "Stack Learner Brand Intro",
    video_description: "Stack Learner Brand Intro",
    tags: ["Logo Animation", "Motion Graphics", "Branding", "Animation"],
    cover_image: "H29MJ6vLbcg",
    publish_date: "2025-04-12",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/H29MJ6vLbcg",
    project_images: ["/placeholder.svg?height=200&width=300"],
    category: "Animation",
    duration: "0:22",
    software_used: ["After Effects"],
  },
  {
    id: 7,
    video_title: "প্রোগ্রামিং এর ফান্ডামেন্টাল শেখা কেন জরুরী?",
    video_description: `আমাদের অনেকের মধ্যে common একটা সমস্যা হলো ফান্ডামেন্টাল না শিখেই কাজ শেখা শুরু করে দেই। ফলাফলস্বরূপ একটা স্টেপ পর্যন্ত পৌঁছানোর পর আমরা আর সামনে আগাতে পারি না। যার কারণে অনেকেই হাল ছেড়ে দেয় আবার অনেকে লেগে থাকে। এই ভিডিওতে আমরা এই বিষয়টাই বুঝার চেষ্টা করবো কেনো ফান্ডামেন্টাল শেখা এত বেশি গুরুত্বপূর্ণ। ভিডিওটি ভালো লাগলে আপনার বন্ধুবান্ধব দের মাঝে share করতে পারেন।`,
    tags: ["Explainer", "Education", "Animation", "Voiceover"],
    cover_image: "MCD9uyZT8Y0",
    publish_date: "2024-01-19",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/MCD9uyZT8Y0?si=W6HDf429dZo7hSQM",
    project_images: [
      "/placeholder.svg?height=200&width=300",
      "/placeholder.svg?height=200&width=300",
    ],
    category: "Explainer",
    duration: "2:43",
    software_used: ["After Effects", "Premiere Pro"],
  },
];
