import {
  Html,
  Head,
  Body,
  Container,
  Text,
  Section,
  Hr,
  // Tailwind, // Keep if you use Tailwind for base styles
  // Column, // Keep if you need multi-column layouts
  // Row, // Keep if you need multi-column layouts
} from "@react-email/components";

type EmailTemplateProps = {
  name: string;
  email: string;
  message: string;
  // You might want to pass your own name here, as the recipient
  // So the template can be more generic for you.
  yourName?: string;
};

export const EmailTemplate = ({
  name,
  email,
  message,
  yourName = "Md. Maruf Sarker", // Default to your name if not provided
}: EmailTemplateProps) => (
  <Html>
    <Head />
    {/* You can uncomment Tailwind if you have it configured and prefer to use it */}
    {/* <Tailwind> */}
    <Body style={body}>
      <Container style={container}>
        {/* Header */}
        <Section style={header}>
          {/* Consider a small, professional logo or icon here if you have one */}
          {/* <img
            src="[YOUR_LOGO_URL_HERE]" // Replace with your actual logo URL (must be publicly accessible)
            width="50"
            height="50"
            alt="Your Logo"
            style={logo}
          /> */}
          <Text style={brand}>
            <span style={emoji}>✨</span> Portfolio Contact Form Submission
          </Text>
        </Section>

        <Hr style={divider} />

        {/* Greeting and Introduction */}
        <Section style={section}>
          <Text style={greetingText}>
            Dear <strong style={highlight}>{yourName}</strong>,
          </Text>
          <Text style={text}>
            You have received a new message from your portfolio website's contact form.
          </Text>
          <Text style={text}>
            The sender's details are as follows:
          </Text>
        </Section>

        {/* Sender Details */}
        <Section style={detailsSection}>
          <Text style={detailItem}>
            <strong>Name:</strong> <span style={detailValue}>{name}</span>
          </Text>
          <Text style={detailItem}>
            <strong>Email:</strong>{" "}
            <a href={`mailto:${email}`} style={link}>
              {email}
            </a>
          </Text>
        </Section>

        {/* Message */}
        <Section style={section}>
          <Text style={text}>Here is the message:</Text>
          <Text style={messageBlock}>{message}</Text>
        </Section>

        {/* Call to Action / Next Steps */}
        <Section style={section}>
          <Text style={text}>
            Please review this message at your earliest convenience.
            I recommend you reply directly to the sender's email address provided above.
          </Text>
          <Text style={closingText}>
            Thank you for staying connected through your portfolio.
          </Text>
        </Section>

        <Hr style={divider} />

        {/* Footer */}
        <Section style={footer}>
          <Text style={footerText}>
            This email was automatically generated by your portfolio's contact system.
          </Text>
          <Text style={footerLink}>
            <a href="https://maruf.vercel.app" style={footerLinkStyle}>
              Visit Your Portfolio
            </a>
          </Text>
        </Section>
      </Container>
    </Body>
    {/* </Tailwind> */}
  </Html>
);

// Styles (adjusted for a slightly more professional and informative tone)
const body = {
  backgroundColor: "#f7f9fc",
  fontFamily: "'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
  padding: "20px 0",
  lineHeight: "1.6",
  color: "#333", // Darker base text color
};

const container = {
  backgroundColor: "#ffffff",
  borderRadius: "12px",
  padding: "30px 25px",
  maxWidth: "600px",
  margin: "0 auto",
  boxShadow: "0 6px 20px rgba(0,0,0,0.08)",
  border: "1px solid #e0e6ed",
};

const header = {
  textAlign: "center" as const,
  marginBottom: "15px",
};

const logo = {
  display: "inline-block",
  marginRight: "10px",
  verticalAlign: "middle",
};

const brand = {
  fontSize: "22px", // Slightly larger for emphasis
  fontWeight: "bold",
  color: "#2c3e50",
  display: "inline-block",
  verticalAlign: "middle",
  letterSpacing: "-0.5px", // Subtle letter spacing
};

const emoji = {
  fontSize: "24px",
  marginRight: "8px",
};

const section = {
  marginBottom: "24px",
  backgroundColor: "#ffffff",
  padding: "0 5px",
};

const detailsSection = {
  backgroundColor: "#f7fafc", // Light background for details
  padding: "15px 20px",
  borderRadius: "8px",
  marginBottom: "24px",
  border: "1px solid #e2e8f0",
};

const text = {
  fontSize: "16px",
  lineHeight: "1.6",
  color: "#34495e",
  marginBottom: "10px",
};

const greetingText = {
  ...text,
  fontSize: "18px",
  fontWeight: "600", // Slightly heavier greeting
};

const closingText = {
  ...text,
  marginTop: "20px", // More space before closing
  fontStyle: "italic" as const,
  color: "#555",
};

const highlight = {
  color: "#2980b9",
  fontWeight: "bold" as const,
};

const detailItem = {
  fontSize: "16px",
  lineHeight: "1.5",
  color: "#34495e",
  marginBottom: "5px",
};

const detailValue = {
  fontWeight: "normal" as const, // Ensure value isn't bold unless intended
};

const messageBlock = {
  backgroundColor: "#ecf0f1",
  padding: "20px",
  borderRadius: "8px",
  fontSize: "16px",
  lineHeight: "1.7",
  color: "#34495e",
  whiteSpace: "pre-line" as const,
  borderLeft: "4px solid #3498db",
  fontFamily: "monospace, sans-serif", // Optional: for code-like messages
};

const link = {
  color: "#3498db",
  textDecoration: "none",
  fontWeight: "600" as const,
};

const divider = {
  borderColor: "#dfe4ed",
  margin: "25px 0",
};

const footer = {
  textAlign: "center" as const,
  marginTop: "20px",
};

const footerText = {
  fontSize: "13px",
  color: "#7f8c8d",
  marginBottom: "8px",
};

const footerLink = {
  marginTop: "5px",
};

const footerLinkStyle = {
  fontSize: "14px",
  color: "#3498db",
  textDecoration: "none",
  fontWeight: "500" as const,
};